### ISSUE TITLE
Left square bracket is included within the ticket link selection

### ISSUE THREAD

**Issue by SunCatMC** [mojira/mojira-discord-bot#103]
## The Bug
When you encase the ticket link within square brackets, in the resulting request the link becomes highlighted blue, aka becomes part of the link's text (the link itself works fine)
(using Android app) 

## Example
![Screenshot_20200826-121943](https://user-images.githubusercontent.com/26610984/91286751-807d6180-e797-11ea-8090-df3b7f0b5ef7.png)
![_20200826_122749](https://user-images.githubusercontent.com/26610984/91286797-8f641400-e797-11ea-95c9-581e01f322fc.JPG)

## Expected behavior
For the square bracket to not be included within the link

**Comment by violine1101** [comment]
As far as I'm aware this is a bug with Discord for Android. This issue does not happen on Desktop. I'm not sure if we can do anything about this.

**Comment by SunCatMC** [comment]
oh, ok
I guess this can be closed then (not gonna do it myself if you don't want to)

**Comment by SunCatMC** [comment]
oh looks like it's fixable, yay!
