### ISSUE TITLE
Add a new '!jira send' command

### ISSUE THREAD

**Issue by SPGoding** [mojira/mojira-discord-bot#112]
## The Problem
Some people accuse the bot of being dumb. The bot needs to reply to them to prove that they are right.

And we might want to use embed sometimes (e.g. sending news with rich links).

## Possible Solution
Adding a new `!jira send <channel> (plain <message>|embed <embed description>)` command (or with some other syntax). By executing this command we could send rich messages in other channels (e.g. `#news`) ~~and fight back when someone curses the bot~~.

**Comment by violine1101** [comment]
I'm not against adding a command like this per se, but I did intentionally not add this command initially.

This (called `!wiki say`) was a feature with Wiki-Bot (where I've contributed a bit in the very beginning), and it ended up causing more issues than it solved. The command was restricted to server moderators, but now it's only accessible to the owner.

The reason for that is that the bot was used by server moderators to argue with other users using the `!wiki say` command, which just caused endless arguments. This idea may seem fun at first, but if used more too often, it quickly gets annoying. On top of that, it was not visible who caused / wrote a bot message without having access to the logs.

This is why I disagree with the reason for why you want to add this command. If this command is added, it should not be used to argue with other users. If at all, it should only be used for creating embeds where necessary or rich-text messages (e.g. for `#welcome`).

As such, in my opinion, this command should only be available to the bot owners as specified in the config.
