### ISSUE TITLE
Show response template without the need to resolve a pending request

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#121]
## The Problem
When you don't want to resolve a pending request but just copy the response template, you currently need to react to one of the options, copy the template, and remove the reaction again.

## Possible Solution
Add an additional reaction to pending requests that is just used to show the response template.

**Comment by Jack-McKalling** [comment]
The bot's workflow would be this:
# user triggers the dedicated "reply" reaction on the internal request (e.g. `:speech_balloon:` emoji)
# bot edits internal request to add the preview
# bot waits a couple of seconds (similar to with other reactions)
# bot removes preview again but leaves the speech balloon

This way people can see that someone (and who) replied to that request, or that particular person could remove it again if they want to repeat the process
