### ISSUE TITLE
Reactions by users are ignored until they write a message

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#125]
## The Bug
When a user has not written a message since the bot has last been restarted and reacts to a pending request message, the bot doesn't react to that reaction.

## Example
N/A

## Expected behavior
The bot should acknowledge the existance of everyone.

**Comment by chandler05** [comment]
I don't think the problem hear is offline users, its just that the bot occasionally forgets that people exist if they don't post.
Anyways, I tested it by turning myself offline and the bot still reacted to my reactions
