### ISSUE TITLE
Accept requests for reports that are 23 hours and 59 minutes old

### ISSUE THREAD

**Issue by dericksonmark** [mojira/mojira-discord-bot#165]
## The Problem
Mojira only specifies report creation time down to the minute (I think). This prevents users from creating requests for reports that are 23 hours and 59 minutes old and some amount of seconds later, which may be misleading.
## Possible Solution
Make sure the ticket is 1439 minutes old rather than 1440 (23:59 intead of 24:00).

**Comment by violine1101** [comment]
> Mojira only specifies report creation time down to the minute (I think).

That's not the case. It specifieds creation time down to the millisecond. However you only see the exact time via the API.

Your message was about 6 seconds too early. The bot's logic is correct and works as intended.

As a technical detail, it's actually not the bot who decides whether the ticket is 24h old. It asks Mojira whether the ticket is 24h old or not.

I'd recommend not to "camp" requests like that, it only wastes your time. It's not like this limit is supposed to be extremely exact.
