### ISSUE TITLE
Add request limit

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#166]
## The Problem
We're currently very backlogged on requests and get more requests every day than we resolve. In order to solve that we need a request limit that doesn't forward requests from a user if that user has posted more than X requests in a single day.

## Possible Solution
Have a data base where pending requests are saved, and if there have been at least X requests by that user in that past 24 hours, deny that request.

This should be configurable on a per-channel basis.

**Comment by Jack-McKalling** [comment]
Further idea notes:

- Limit applies to each user individually
- Possibly let the limit of requests for a user be based off of their existing pending request count within our internal channel (as opposed to database)
- When limit reached;
  1. user's request gets auto denied by the bot with another unique emoji
  2. bot also sends a personal message to said user (either timed with a ping or just a DM), similar to the existing <24h mechanic
  3. request doesn't get forwarded to internal channel

**Comment by chandler05** [comment]
I don't think its fair to save the requests to a database and check from that, we don't want to limit people if we are actively resolving the requests, so I think it is best to read from the internal channel like Jack mentioned.
