### ISSUE TITLE
When replying to a message with a bug report, reply to the same message with the embed

### ISSUE THREAD

**Issue by chandler05** [mojira/mojira-discord-bot#192]
## The Problem
When replying to a message with a ticket key, that message gets deleted and loses its properties as a reply.
## Possible Solution
Send the embed as a reply to the same message, with the same ping setting.

**Comment by violine1101** [comment]
Do you have an example for this? I'm not quite sure what exactly the issue is here. A screenshot would be helpful

**Comment by chandler05** [comment]
Exhibit A: user replies to a message with ticket to show them that ticket
![Screenshot_20210507-052915.png](https://user-images.githubusercontent.com/66492208/117438351-0f31a900-aef7-11eb-964e-99d8886499ef.png)

Exhibit B: MojiraBot deletes the message and creates an embed in a new message, not preserving the reply
![Screenshot_20210507-052936.png](https://user-images.githubusercontent.com/66492208/117438447-2cff0e00-aef7-11eb-89f3-3442bb0578af.png)

**Comment by chandler05** [comment]
This can't be implemented until Discord.js version 13 releases, as they currently don't support inline replies.

**Comment by violine1101** [comment]
Aah, thanks. Right, Discord has that reply feature now. Forgot about that.
