### ISSUE TITLE
The response message for requests takes up too much space

### ISSUE THREAD

**Issue by NeunEinser** [mojira/mojira-discord-bot#22]
The response message is something that currently can be turned on to be posted per request. It contains a codeblock with a message like this for copying a response for the request:
```
@User12345 https://discordapp.com/channels/647810384031645728/648555618994618378/683450920612266038
>MC-1234 duplicates MC-123
xxx
```
This is currently disabled on the server because it takes up too much space per request.

Options I see to mitigate this:
* Add the message only once a volunteer has reacted with an emoji
* Include the message in the request log instead.

**Comment by misode** [comment]
What about only showing this on the request that has received a volunteer reaction most recently? Meaning you can copy the message just after reacting.

**Comment by NeunEinser** [comment]
Do you mean for the 2nd option?
I dunno, the log doesn't matter too much imo.
For the 1st option, the message gets deleted pretty quickly anyways after it has been resolved, so that wouldn't be an issue.
