### ISSUE TITLE
The bot currently does not seem to post old requests to the internal request channel

### ISSUE THREAD

**Issue by NeunEinser** [mojira/mojira-discord-bot#24]
This could potentially become an issue when requests are posted during a downtime.
It would be good if the bot would scan for messages without any reaction in the request channel after starting.

**Comment by Jack-McKalling** [comment]
If this gets implemented, I could also safely stop manually tracking the pre-bot requests. But I don't mind doing it. Although in a case of downtime, this will still be an issue. I cannot track those requests

**Comment by Jack-McKalling** [comment]
The pre-bot requests have been finished recently so I already stopped tracking manually. But I can't track those that are sent during downtime, as essentially I'm not aware of it when it is down. Others have been doing it but we need this automated too. What is required for automatically letting the bot catch up with any backlog of missed requests?

**Comment by NeunEinser** [comment]
I would probably just scan for all messages send in the requests channel on startup, create a message for every one that has not yet a reaction added to it, until hitting the first message which has a reaction by MojiraBot.
Not sure if there might be a more clean way of doing it.
