### ISSUE TITLE
Request blocking

### ISSUE THREAD

**Issue by chandler05** [mojira/mojira-discord-bot#240]
## The Problem
It would be nice to be able to manually block specific users from creating requests for certain periods of time.
## Possible Solution
Bot command with role that prevents using request channels.

**Comment by Jack-McKalling** [comment]
This would be useful if we notice a certain type of abuse, or if instructions appear not effective for someone.

**Comment by dericksonmark** [comment]
This isn't something that's necessary anymore, so I'll close this for now.
