### ISSUE TITLE
Upgrade discord.js to v12

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#28]
Version 12 of discord.js has been released yesterday: https://github.com/discordjs/discord.js/releases/tag/12.0.0

This appears to be quite a large update, might be worth waiting for all existing PRs to be merged in order to upgrade the bot.

**Comment by urielsalis** [comment]
I usually wait a week/month depending on how big the changes after a release, so potential bugs are found and fixed

**Comment by NeunEinser** [comment]
From what I can tell so far, most of the stuff is pretty easy to update. However, our EventRegistry might need some rethinking as the general `public on(event: string, listener: Function): this;` seems to have been removed, though I can't seem to find a mention of this in https://discordjs.guide/additional-info/changes-in-v12.html#client.
