### ISSUE TITLE
Allow to add links / progress indicators to internal requests

### ISSUE THREAD

**Issue by NeunEinser** [mojira/mojira-discord-bot#29]
I don't know how doable this one is, but it would be cool to have some way of allowing to add messages to internal requests, for example using a command.
This would be useful if a request needs an internal discussion to show other volunteers that the request is already in progress (since reacting with an hourglass isn't an option anymore).

Example of a usecase:
![image](https://user-images.githubusercontent.com/12124394/75704297-69aef400-5cb9-11ea-90dc-7761279c5f18.png)

**Comment by Jack-McKalling** [comment]
Another idea that would also allow us to add info to an internal request, is to just type it as a regular message to the channel, while including the full link to the internal request in question.

So if the bot would detect such a message link from any non mojirabot user in that channel, it would copy the text into the internal request by means of a bullet list, and delete the user's message.

Do note that if we let the bot edit its message above the embed, it needs to make sure it doesn't interfere with the existing reply template, which you can activate with the speech baloon emoji.

**Comment by SPGoding** [comment]
The bot could also delay the deletion of our own message for a few seconds, so we could jump back to where we were at by clicking the message link we just sent.
