### ISSUE TITLE
The bot messes up the rich link in pending requests for links not using /browse/

### ISSUE THREAD

**Issue by NeunEinser** [mojira/mojira-discord-bot#30]
Example:
![image](https://user-images.githubusercontent.com/12124394/76163942-e541f280-614a-11ea-91cb-8cfb06196050.png)
> https://bugs.mojang.com/projects/MC/issues/MC-174207 dupe of https://bugs.mojang.com/browse/MC-173725

![image](https://user-images.githubusercontent.com/12124394/76163953-f854c280-614a-11ea-8e24-e771911633bd.png)
> https://bugs.mojang.com/projects/MC/issues/[MC-174207](https://bugs.mojang.com/browse/MC-174207) dupe of [MC-173725](https://bugs.mojang.com/browse/MC-173725)

This is probably because the `ticketLinkRegex` does not match that type of url.

**Comment by SPGoding** [comment]
Does this type of URL really work? e.g. https://bugs.mojang.com/projects/MC/issues/MC-4

**Comment by NeunEinser** [comment]
It seems to depend on the ticket ID for some weird reason.
https://bugs.mojang.com/projects/MC/issues/MC-173740 for example gets me to [MC-173740](https://bugs.mojang.com/browse/MC-173740).
Maybe because of the filter view older tickets can't be accessed like that?

**Comment by NeunEinser** [comment]
Ah yes. The filter view has a max of 10 pages as it looks like. Anything that does not appear on the first 10 pages cannot be accessed with a link like that.
But when browsing issues, people can still get these kinds of links. It would be saver to always convert to a /browse/ link.
