### ISSUE TITLE
Bot does not register role removals after being restarted

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#32]
When removing a reaction from a role selection message, the bot no longer seems to be able to register that removal and won't remove the role, in case the role reaction was added before the bot was started.

**Comment by NeunEinser** [comment]
Works on my machine 🤔

**Comment by urielsalis** [comment]
Bot was not up when it happened?

**Comment by urielsalis** [comment]
Bot was not up when it happened?

**Comment by NeunEinser** [comment]
Ah, apparently it doesn't work trigger for emojis being removed that were added before the last restart.
It always works when removing, re-adding and removing again the emoji for me.

As far as I can tell, the event does simply not trigger on the API's side of things, so not much we can do about that I guess.

**Comment by SPGoding** [comment]
This can be fixed after #28 is resolved by adding this option to the client: `{ partials: ['REACTION'] }`.
