### ISSUE TITLE
MojiraBot only reacts to the last 50 request messages prior to the previous restart

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#56]
The bot does not react to reactions to request messages prior to 2020-06-19 18:00 UTC for some reason.

**Comment by amnotbananaama** [comment]
This sounds about when you restarted the bot to implement https://github.com/mojira/mojira-discord-bot/pull/55. It's likely that the bot doesn't recognize old requests from before it was restarted, as these are probably not preserved between restarts.


My naive fix would be either:

a) Log all currently outstanding requests in a file locally, and load that file upon the boy's startup. When a request is resolved by a moderator or helper delete the request from the file.

b) Implement a restart system such that substantial portions of the bot's code can be changed without the bot being taken offline.

In my opinion solution A would be preferable, as there are circumstances where the Mojira bot could go offline unexpectedly (power or internet loss) that solution B could not account for.

**Comment by SPGoding** [comment]
https://github.com/mojira/mojira-discord-bot/blob/78c8bac1347b65932fba2435c44328568c976c82/src/MojiraBot.ts#L89

🤔 Messages in internal channels are fetched on startup, so restarting shouldn't have impact on it.
