### ISSUE TITLE
Automatically delete messages that contain profanity/NSFW content

### ISSUE THREAD

**Issue by chandler05** [mojira/mojira-discord-bot#57]
This is usually done by hand already and would be helpful if it was done automagically

**Comment by urielsalis** [comment]
I think we have Dyno doing this

**Comment by chandler05** [comment]
So does that mean If I put any swear words in a message, it will be deleted? I'm pretty sure I've seen swearing on the discord before..

**Comment by violine1101** [comment]
We currently don't have any automated tool to delete NSFW stuff. But in my opinion the server is small enough and our moderator team is large enough to handle everything manually.

When it becomes an issue though it would be way easier to add an additional third-party bot specialized on this kind of stuff as opposed to trying to reinvent the wheel.

**Comment by NeunEinser** [comment]
I agree with violine here. It would make more sense to add another well-established bot that deals with it if it ever becomes a problem.
