### ISSUE TITLE
Ping user of '!jira ping' command when responding with 'Pong!'

### ISSUE THREAD

**Issue by dericksonmark** [mojira/mojira-discord-bot#72]
Occasionally, a user deletes their !jira ping comment, leaving a random 'Pong!' by MojiraBot in #bot-commands. It would be better if the bot could ping the user of the command (for example "@markderickson Pong!"). This will make it easier to see that the pong wasn't just a reaction to an older message, but a reaction to a deleted message.

An example of this can be found at https://discordapp.com/channels/647810384031645728/647814935572643840/739336733002301542.

**Comment by misode** [comment]
This is the case with every command and with every bot I know of. I don't see how this is a problem when the user deletes their own message.

**Comment by violine1101** [comment]
It would perhaps be a good idea if the bot pinged whoever used the ping command, so that it's easily visible who triggered it.

**Comment by dericksonmark** [comment]
Hi there!
That sounds like a better idea to ping the user of the command instead of deleting the response, it would likely clear up any confusion about which command the bot is responding to. Should I edit the ticket?
