### ISSUE TITLE
Publish messages sent to #java-fixes

### ISSUE THREAD

**Issue by urielsalis** [mojira/mojira-discord-bot#73]
Call POST /channel/channelid/message/messageid/crosspost to publish the message for the fixes channel

**Comment by violine1101** [comment]
Investigating whether this is possible to do with our current architecture or if this is blocked by #28

**Comment by urielsalis** [comment]
We can make a normal call, its undocumented so discord.js v12 might not also have it

**Comment by violine1101** [comment]
Yeah, but question is, does discord.js provide a way to authenticate the POST call? Doesn't seem like it does and we'd need to use some workaround.

For discord.js 12, the PR is currently pending (4089).
