### ISSUE TITLE
Filter feed misses bug reports that have been fixed but are still in cache

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-discord-bot#88]
## The bug
When a ticket has been fixed, is reopened and then is fixed again, it is not catched by the filter feed because it's still stuck in the ticket cache.

## Suggested solution
Instead of the cache, keep a property "lastRun" and only include tickets that have been "resolved > lastRun".

**Comment by Jack-McKalling** [comment]
For example https://bugs.mojang.com/browse/MC-219155. By the time the report was fixed for 21w17a, it already had 21w11a as the fix version.
